#! /bin/bash
#SBATCH -p q_student
#SBATCH --time=10:00
#SBATCH -N 32
#SBATCH --ntasks-per-node=1   # start 4 processes per node
#SBATCH --cpu-freq=High       # set CPU frequency to maximum
#SBATCH SKIP_VALIDATION=1
srun ./graph500_reference_bfs 15

