#! /bin/bash
#SBATCH -p q_student
#SBATCH --time=5:00
#SBATCH -N 32
#SBATCH --ntasks-per-node=32   # start 4 processes per node
#SBATCH --cpu-freq=High       # set CPU frequency to maximum
export SCALE=8
srun ./graph500_reference_bfs $SCALE  > out-$SCALE-$SLURM_JOB_NUM_NODES-$SLURM_NTASKS_PER_NODE.log

