#! /bin/bash
#SBATCH -p q_student_low_long
#SBATCH --time=20:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=32   # start 4 processes per node
#SBATCH --cpu-freq=High       # set CPU frequency to maximum
export SCALE=26
srun ./graph500_reference_bfs $SCALE  > out-$SCALE-$SLURM_JOB_NUM_NODES-$SLURM_NTASKS_PER_NODE.log

